name: Docker Build Production Image
on: [push, pull_request]

jobs:
  build-stable:
    name: Build latest stable version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the production Docker image
        run: docker build -t decred/dcrros:$(date +%s) .
